### ISSUE TITLE
Singularity image not capable of being pulled

### ISSUE THREAD

**Issue by gavinkurgan** [dcouvin/CRISPRCasFinder#11]
Hello!

I have tried pulling from your singularity image using the following command
```
singularity pull --name CRISPRCasFinder shub://dcouvin/CRISPRCasFinder:4.2.18
```
However I receive the following error:
```
ERROR Cannot find image. Is your capitalization correct?
```

Is it possible that your shub acct is not publicly available or something is not correct in the command provided? If the fix is on my end, please just let me know!

Thanks!

**Comment by bneron** [comment]
CRISPRCasFinder is not in dcouvin collections but in bneron
https://singularity-hub.org/collections/1625

**Comment by dcouvin** [comment]
Please note that a new singularity container is available at: https://crisprcas.i2bc.paris-saclay.fr/Home/Download
