### ISSUE TITLE
General Search not working

### ISSUE THREAD

**Issue by rkruegs123** [dcouvin/CRISPRCasFinder#12]
I am trying to identify all cas genes in a sequence _even if they don't belong to a subgroup, or constitute all of the mandatory genes for a subgroup._ For example, there is a sequence that I know has csy3 and cas6, but as those do not constitute all of the necessary components for a I-F system, there are no Cas clusters returned.

On the online version, you can change "Subtyping" to "General" to return these clusters. However, when I use -def G or --definition General on the command line version, it still does not seem to return these clusters. I suspect that the General feature is broken?

**Comment by dcouvin** [comment]
Dear @rkruegs123, thank you for your message. We will check this feature and try to fix it. The last command line version is in development for the moment. However, you can also use one of the former versions (https://github.com/dcouvin/CRISPRCasFinder/archive/release-4.2.19.tar.gz) to see if the error is still occurring. Thanks again.

**Comment by rkruegs123** [comment]
Thank you! Also, do you have any idea of when support will be added for some of the newer cas proteins, such as Cas 12 and 13?

**Comment by dcouvin** [comment]
I do not know yet when newer Cas proteins will be available, but I'll let you know as soon as possible. Thank you.

**Comment by rkruegs123** [comment]
Thank you for your help. I tried it with the old release and it still did not work - any thoughts?

**Comment by dcouvin** [comment]
Did you also try with the -meta option. It may hopefully work with this option.

**Comment by rkruegs123** [comment]
This worked - thank you!
