### ISSUE TITLE
run command locally and submission to website generate different results.

### ISSUE THREAD

**Issue by limin321** [dcouvin/CRISPRCasFinder#16]
Hi 
I installed CRISPRCasFinder in my mac and run 
perl ./../CRISPRCasFinder.pl -in ../../hybrid_assembly/assembly_fasta\&gfa/hybrid_fasta/Yol001.fasta -cas -cf CasFinder-2.0.2 -def G -keep    locally, and it is not able to find any cas genes and crispr system. However, when I submit the same genome to websit, https://crisprcas.i2bc.paris-saclay.fr/CrisprCasFinder/Viewing/637185279057211761. It is able to find 2 CRISPR and 1 CAS.
Could anyone please help what might be the resson of my issue?  your help will be greatly appreciated.

By the way, when I install CRISPRCasFinder , I have to run 
$ export PERL5LIB=/usr/local/libexec/crisprcas/lib/perl5:/Users/dklabuser/Scripts/cgview_comparison_tool/lib/bioperl-1.2.3:/Users/dklabuser/Scripts/cgview_comparison_tool/lib/perl_modules:

Then, run $ perl ./../CRISPRCasFinder.pl -in ../../hybrid_assembly/assembly_fasta\&gfa/hybrid_fasta/Yol001.fasta -cas -cf CasFinder-2.0.2 -def G -keep 

I don't know what is wrong with this issue either. If anyone can help, that will be really great.

Best
Limin

**Comment by dcouvin** [comment]
Dear Limin, 
Thank you for your message.
This difference in results between your Mac and the website could be due to differences in versions of software dependencies:
- on the website, version v2.0.3 of CasFinder is potentially used (this version is not yet available).
- results concerning CRISPR prediction may also differ in function of the version of several dependencies such as EMBOSS.

Please try on another system like Linux if possible.

Best,
David

**Comment by graceblackwell** [comment]
Hi David, 
I am also having a similar problem, where the website is detecting cas genes but when using the singularity image to run the analysis on the same assembly, it doesn't find any. When do you expect v2.0.3 to be released?
Best, 
Grace

**Comment by dcouvin** [comment]
Hi Grace,
Thank you for your message.
Unfortunately I do not know the release date of the next version of CasFinder. I will try to ask colleagues from Pasteur Institute in Paris for more information. Maybe Bertrand (@bneron ) could provide more precision on this issue.
I will let you know when I have more information.
Best,
David

**Comment by graceblackwell** [comment]
Hi David,
Thanks that would be great! I am hoping to apply it to quite a large database of assemblies and thought it would be best to apply it with the most up to date database if possible. 
Best, 
Grace

**Comment by graceblackwell** [comment]
Hi David, 
Any updates?
Best, 
Grace

**Comment by dcouvin** [comment]
Dear Grace,
Good news!
We have just received the new version of CasFinder.
The updated CRISPRCasFinder will be available soon.
Best,
David

**Comment by limin321** [comment]
Thanks. everyone .  I am still waiting for the new version to release.
That's an exciting news.

Best,
limin

**Comment by graceblackwell** [comment]
Great news! Will keep my eye out :) Thanks for following it up.
Best, 
Grace

**Comment by dcouvin** [comment]
Dear Grace and Limin,
The updated CasFinder has been added to the tool. Do not hesitate if you encounter a problem using the updated tool. 
Best,
David

**Comment by limin321** [comment]
excellent.  Thank you very much. That's really an exciting news.  I am
gonna try soon.

Great appreciation for your work.
Best.

**Comment by dcouvin** [comment]
Thank you Limin,
Please note that this version of CasFinder (2.0.3) does not correspond to the last update (Makarova et al., 2020 ; https://doi.org/10.1038/s41579-019-0299-x). This change will be performed soon thanks to colleagues from Institut Pasteur in Paris. Thank you for your patience.
Best,
David

**Comment by limin321** [comment]
> Thank you Limin,
> Please note that this version of CasFinder (2.0.3) does not correspond to the last update (Makarova et al., 2020 ; https://doi.org/10.1038/s41579-019-0299-x). This change will be performed soon thanks to colleagues from Institut Pasteur in Paris. Thank you for your patience.
> Best,
> David

Hi David,
Thank you so much for the notes.  
I just installed the new version of  CasFinder (2.0.3). The installation process goes pretty well, but when I test,  I run into some issue. 
```bash
dklabuser$ perl CRISPRCasFinder.pl -h
```
here is the output. 
```
Sysexits.c: loadable library and perl binaries are mismatched (got handshake key 0xd800080, needed 0xdb00080)
```
any thoughts what might be the issue? and how to solve it?

Thanks.
Best, 
Limin

**Comment by dcouvin** [comment]
Hi Limin,
Thank you for your message. I have not seen this error before, but I will try to solve it. Which operating system are you using? this error could be caused by the fact that your libperl version and your perl version are not the same. Maybe these links could help: https://stackoverflow.com/questions/45000585/listutil-c-loadable-library-and-perl-binaries-are-mismatched-got-handshake-key ; https://askubuntu.com/questions/1175697/loadable-library-and-perl-binaries-are-mismatched ; https://github.com/pgbackrest/pgbackrest/issues/687   
I hope these links will help
Best,
David

**Comment by limin321** [comment]
> Hi Limin,
> Thank you for your message. I have not seen this error before, but I will try to solve it. Which operating system are you using? this error could be caused by the fact that your libperl version and your perl version are not the same. Maybe these links could help: https://stackoverflow.com/questions/45000585/listutil-c-loadable-library-and-perl-binaries-are-mismatched-got-handshake-key ; https://askubuntu.com/questions/1175697/loadable-library-and-perl-binaries-are-mismatched ; [pgbackrest/pgbackrest#687](https://github.com/pgbackrest/pgbackrest/issues/687)
> I hope these links will help
> Best,
> David



> Hi Limin,
> Thank you for your message. I have not seen this error before, but I will try to solve it. Which operating system are you using? this error could be caused by the fact that your libperl version and your perl version are not the same. Maybe these links could help: https://stackoverflow.com/questions/45000585/listutil-c-loadable-library-and-perl-binaries-are-mismatched-got-handshake-key ; https://askubuntu.com/questions/1175697/loadable-library-and-perl-binaries-are-mismatched ; [pgbackrest/pgbackrest#687](https://github.com/pgbackrest/pgbackrest/issues/687)
> I hope these links will help
> Best,
> David

Hi David,
Mine is macOS Version 10.15.2, I tried to solve the issue following the link you sent to me, but I don't think I understand that at all.  
When I run the following code:
```
$ ls -lah /usr/lib/x86_64-linux-gnu/libperl.so
```
Here is the output:
```
ls: /usr/lib/x86_64-linux-gnu/libperl.so: No such file or directory
```
feels like my mac doesn't have libper.

while running the 
```
$ perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for darwin-thread-multi-2level

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

```
the perl is there.  When I installed the old version of CRISPRCaseFinder, I didn't have this problem.

Thanks.

**Comment by dcouvin** [comment]
Hi Limin,
Thank you for your message. Indeed, I didn't try it on MacOS. Maybe @bneron could help us on this issue. There is a specific installation for Mac users. Maybe you could try to run directly "CRISPRCasFinder.pl -h" or "CRISPRCasFinder -h" without the perl command. please look at the user manuel "CRISPRCasFinder_Viewer_manual.pdf".
You could also try to copy directly the main perl script and the new CasFinder folder in your previous installation repository.
I hope these will help.
Best,
David

**Comment by limin321** [comment]
> Hi Limin,
> Thank you for your message. Indeed, I didn't try it on MacOS. Maybe @bneron could help us on this issue. There is a specific installation for Mac users. Maybe you could try to run directly "CRISPRCasFinder.pl -h" or "CRISPRCasFinder -h" without the perl command. please look at the user manuel "CRISPRCasFinder_Viewer_manual.pdf".
> You could also try to copy directly the main perl script and the new CasFinder folder in your previous installation repository.
> I hope these will help.
> Best,
> David

Hi Davis,
You are right.  I followed your suggestion:  copy directly the main perl script and the new CasFinder folder in your previous installation repository.   and it works. I am able to get the same results as the one i got from website.  Really appreciate that. 

Best,
Limin

**Comment by dcouvin** [comment]
Great ! ;-)

**Comment by limin321** [comment]
Hi David,

I am so sorry to bother you again.  I made the code work yesterday, while
today, when I ran it no output again. Here is the output from yesterday:

```
(crispr) KluepfelLabMBP01:test dklabuser$ perl ../CRISPRCasFinder.pl -in
/Users/dklabuser/limin/hybrid_assembly/assembly_fasta_gfa/But01.fasta -cas
-log -out But001 -cf my_CasFinder -def G
################################################################
# --> Welcome to ../CRISPRCasFinder.pl (version 4.2.20)
################################################################


vmatch2 is...............OK
mkvtree2 is...............OK
vsubseqselect2 is...............OK
fuzznuc (from emboss) is...............OK
needle (from emboss) is...............OK


[21:59:44] ---> Results will be stored in But001


Sequence number 1..  ( Input file: But001_circh.fna, Sequence ID:
But001_circh, Sequence name = Unknown )

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

DRs_1 2 seqs, lengths min 23, max 23, avg 23
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 1
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 2
00:00:00      1 MB(0%)  Iter   1  100.00%  Align node
00:00:00      1 MB(0%)  Iter   1  100.00%  Root alignment

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

Spacers_1 1 seqs, lengths min 30, max 30, avg 30

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

DRs_2 2 seqs, lengths min 24, max 24, avg 24
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 1
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 2
00:00:00      1 MB(0%)  Iter   1  100.00%  Align node
00:00:00      1 MB(0%)  Iter   1  100.00%  Root alignment

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

Spacers_2 1 seqs, lengths min 54, max 54, avg 54
Nb of CRISPRs in this sequence = 2

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

DRs_1 2 seqs, lengths min 23, max 23, avg 23
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 1
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 2
00:00:00      1 MB(0%)  Iter   1  100.00%  Align node
00:00:00      1 MB(0%)  Iter   1  100.00%  Root alignment

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

Spacers_1 1 seqs, lengths min 30, max 30, avg 30

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

DRs_2 2 seqs, lengths min 24, max 24, avg 24
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 1
00:00:00      1 MB(0%)  Iter   1  100.00%  K-mer dist pass 2
00:00:00      1 MB(0%)  Iter   1  100.00%  Align node
00:00:00      1 MB(0%)  Iter   1  100.00%  Root alignment

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

Spacers_2 1 seqs, lengths min 54, max 54, avg 54


prodigal installation is.............OK
macsyfinder installation is...........OK
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...2759235 bp seq created, 58.87 pct GC
Locating all potential starts and stops...169844 nodes
Looking for GC bias in different frames...frame bias scores: 0.66 0.24 2.11
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (2759235 bp)...done!
MacSyFinder's results will be stored in
But01_27_5_2020_21_59_44/casfinder_But001_circh/
Analysis launched on
/Users/dklabuser/limin/CRISPRCasFinder-master/test/But01_27_5_2020_21_59_44/prodigal_But001_circh/But001_circh.faa
for system(s):
- CAS-TypeIC
- CAS-TypeIB
- CAS-TypeIIIU
- CAS-TypeIU
- CAS-TypeIIIB
- CAS-TypeIA
- CAS-TypeIIIA
- CAS-TypeIE
- CAS-TypeIIB
- CAS-TypeIIU
- CAS-TypeID
- CAS-TypeIF
- CAS-TypeIIA
- CAS-TypeU
- CAS

************************************
 Analyzing clusters
************************************



****************************************************
******* Report scattered/uncompleted systems *******
****************************************************

******************************************

******************************************
Building reports of detected systems

Counter()
******************************************

Nb of Cas in this sequence = 0

Sequence number 2..  ( Input file: But001_lich.fna, Sequence ID:
But001_lich, Sequence name = Unknown )
Nb of CRISPRs in this sequence = 0


prodigal installation is.............OK
macsyfinder installation is...........OK
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...2117117 bp seq created, 58.67 pct GC
Locating all potential starts and stops...131890 nodes
Looking for GC bias in different frames...frame bias scores: 0.69 0.26 2.05
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (2117117 bp)...done!
MacSyFinder's results will be stored in
But01_27_5_2020_21_59_44/casfinder_But001_lich/
Analysis launched on
/Users/dklabuser/limin/CRISPRCasFinder-master/test/But01_27_5_2020_21_59_44/prodigal_But001_lich/But001_lich.faa
for system(s):
- CAS-TypeIC
- CAS-TypeIB
- CAS-TypeIIIU
- CAS-TypeIU
- CAS-TypeIIIB
- CAS-TypeIA
- CAS-TypeIIIA
- CAS-TypeIE
- CAS-TypeIIB
- CAS-TypeIIU
- CAS-TypeID
- CAS-TypeIF
- CAS-TypeIIA
- CAS-TypeU
- CAS

************************************
 Analyzing clusters
************************************



****************************************************
******* Report scattered/uncompleted systems *******
****************************************************

******************************************

******************************************
Building reports of detected systems

Counter()
******************************************

Nb of Cas in this sequence = 0

Sequence number 3..  ( Input file: But001_pAt.fna, Sequence ID: But001_pAt,
Sequence name = Unknown )
Nb of CRISPRs in this sequence = 0


prodigal installation is.............OK
macsyfinder installation is...........OK
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...647758 bp seq created, 57.06 pct GC
Locating all potential starts and stops...38795 nodes
Looking for GC bias in different frames...frame bias scores: 0.76 0.26 1.98
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (647758 bp)...done!
MacSyFinder's results will be stored in
But01_27_5_2020_21_59_44/casfinder_But001_pAt/
Analysis launched on
/Users/dklabuser/limin/CRISPRCasFinder-master/test/But01_27_5_2020_21_59_44/prodigal_But001_pAt/But001_pAt.faa
for system(s):
- CAS-TypeIC
- CAS-TypeIB
- CAS-TypeIIIU
- CAS-TypeIU
- CAS-TypeIIIB
- CAS-TypeIA
- CAS-TypeIIIA
- CAS-TypeIE
- CAS-TypeIIB
- CAS-TypeIIU
- CAS-TypeID
- CAS-TypeIF
- CAS-TypeIIA
- CAS-TypeU
- CAS
No Cas results
Nb of Cas in this sequence = 0

Sequence number 4..  ( Input file: But001_pTi.fna, Sequence ID: But001_pTi,
Sequence name = Unknown )
Nb of CRISPRs in this sequence = 0


prodigal installation is.............OK
macsyfinder installation is...........OK
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...177577 bp seq created, 56.08 pct GC
Locating all potential starts and stops...10086 nodes
Looking for GC bias in different frames...frame bias scores: 1.14 0.25 1.61
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (177577 bp)...done!
MacSyFinder's results will be stored in
But01_27_5_2020_21_59_44/casfinder_But001_pTi/
Analysis launched on
/Users/dklabuser/limin/CRISPRCasFinder-master/test/But01_27_5_2020_21_59_44/prodigal_But001_pTi/But001_pTi.faa
for system(s):
- CAS-TypeIC
- CAS-TypeIB
- CAS-TypeIIIU
- CAS-TypeIU
- CAS-TypeIIIB
- CAS-TypeIA
- CAS-TypeIIIA
- CAS-TypeIE
- CAS-TypeIIB
- CAS-TypeIIU
- CAS-TypeID
- CAS-TypeIF
- CAS-TypeIIA
- CAS-TypeU
- CAS
No Cas results
Nb of Cas in this sequence = 0

Sequence number 5..  ( Input file: But001_contig5.fna, Sequence ID:
But001_contig5, Sequence name = Unknown )
Nb of CRISPRs in this sequence = 0


prodigal installation is.............OK
macsyfinder installation is...........OK
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Metagenomic, Phase:  Training
Initializing training files...done!
-------------------------------------
Request:  Metagenomic, Phase:  Gene Finding
Finding genes in sequence #1 (50253 bp)...done!
MacSyFinder's results will be stored in
But01_27_5_2020_21_59_44/casfinder_But001_contig5/
Analysis launched on
/Users/dklabuser/limin/CRISPRCasFinder-master/test/But01_27_5_2020_21_59_44/prodigal_But001_contig5/But001_contig5.faa
for system(s):
- CAS-TypeIC
- CAS-TypeIB
- CAS-TypeIIIU
- CAS-TypeIU
- CAS-TypeIIIB
- CAS-TypeIA
- CAS-TypeIIIA
- CAS-TypeIE
- CAS-TypeIIB
- CAS-TypeIIU
- CAS-TypeID
- CAS-TypeIF
- CAS-TypeIIA
- CAS-TypeU
- CAS
No Cas results
Nb of Cas in this sequence = 0
#### Statistics on CRISPRs orientation by CRISPRCasFinder vs.
CRISPRDirection

Total number of CRISPRs arrays found = 2
Number of perfect macthes between CRISPRCasFinder and CRISPRDirection = 0
Number of Forward by CRISPRCasFinder = 2
Number of Forward by CRISPRDirection = 0
Number of Reverse by CRISPRCasFinder = 0
Number of Reverse by CRISPRDirection = 0

Number of unoriented by CRISPRCasFinder = 0
Number of unoriented by CRISPRDirection = 2
Orientations count file created:
But01_27_5_2020_21_59_44/crisprs_orientations_count.tsv

Deleting secondary folders/files...
All Cas = 0

[22:0:9] Thank you for using ../CRISPRCasFinder.pl! Thank you for your
patience!

[22:0:9] The script lasted: 0 year(s) 0 month(s) 0 day(s) , 0 hour(s) 0
minute(s) 25 second(s)

```
############################################################
Then I ran exactly the same code today, it looks like this:
#################################################
```

(crispr) KluepfelLabMBP01:test2 dklabuser$ perl ../CRISPRCasFinder.pl -in
/Users/dklabuser/limin/data_analysis/CRISPRCas_agro/cspr_fna/Yol001.fasta
-cas -log -out Yol001 -cf my_CasFinder -def G

################################################################

# --> Welcome to ../CRISPRCasFinder.pl (version 4.2.20)

################################################################



vmatch2 is...............OK

mkvtree2 is...............OK

vsubseqselect2 is...............OK

fuzznuc (from emboss) is...............OK

needle (from emboss) is...............OK



[11:29:24] ---> Results will be stored in Yol001


#### Statistics on CRISPRs orientation by CRISPRCasFinder vs.
CRISPRDirection


Total number of CRISPRs arrays found = 0

Number of perfect macthes between CRISPRCasFinder and CRISPRDirection = 0

Number of Forward by CRISPRCasFinder = 0

Number of Forward by CRISPRDirection = 0

Number of Reverse by CRISPRCasFinder = 0

Number of Reverse by CRISPRDirection = 0


Number of unoriented by CRISPRCasFinder = 0

Number of unoriented by CRISPRDirection = 0

Orientations count file created:
Yol001_28_5_2020_11_29_24/crisprs_orientations_count.tsv


Deleting secondary folders/files...

All Cas = 0


[11:29:24] Thank you for using ../CRISPRCasFinder.pl! Thank you for your
patience!


[11:29:24] The script lasted: 0 year(s) 0 month(s) 0 day(s) , 0 hour(s) 0
minute(s) 0 second(s)
```
There is no error message, and I have no idea what is going on?  Any
thoughts on that? or any suggestion?

Thanks a lot.
Best,

**Comment by limin321** [comment]
I know I use different input fasta, actually I tested Yol001 yesterday and
also confirmed the website version, there is supposed to have 2 crispr from
yesterday's output.

[image: Screen Shot 2020-05-28 at 11.42.41 AM.png]

Really confused since there is no error message.

Really appreciate all your help.
