### ISSUE TITLE
perl module issues

### ISSUE THREAD

**Issue by tushar-ahmed** [dcouvin/CRISPRCasFinder#21]
Hello there, 

Perl modules required for CRISPRCasFinder.pl script are conflicting with my Miniconda environment. 

CRISPRCasFinder worked perfectly if I remove Miniconda, but when Minoconda is there, CRISPRCasFinder can not locate modules. Following error occurs:

hishir@d3w:~/CRISPRCasFinder$ perl CRISPRCasFinder.pl
Can't locate Date/Calc.pm in @INC (you may need to install the Date::Calc module) (@INC contains: /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2 /home/shishir/miniconda3/envs/genomics/lib/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/5.26.2 .) at CRISPRCasFinder.pl line 25.
BEGIN failed--compilation aborted at CRISPRCasFinder.pl line 25.

not only for Date::Calc module, but also for some others. 
CRISPRCasFinder is looking for Perl modules in the Conda environment instead of root. 

How can I solve the issue to make the CRISPRCasFinder to look for scripts at the root directory? 
Here is the path to Perl Modules:- 

shishir@d3w:~/CRISPRCasFinder$ locate Date/Calc.pm
/home/shishir/.cpan/build/Date-Calc-6.4-0/blib/lib/Date/Calc.pm
/home/shishir/.cpan/build/Date-Calc-6.4-0/lib/Date/Calc.pm
/home/shishir/.cpan/build/Date-Calc-6.4-1/blib/lib/Date/Calc.pm
/home/shishir/.cpan/build/Date-Calc-6.4-1/lib/Date/Calc.pm
/home/shishir/.cpanm/work/1595698278.17997/Date-Calc-6.4/lib/Date/Calc.pm
/usr/local/share/perl/5.30.0/Date/Calc.pm
/usr/share/perl5/Date/Calc.pm

shishir@d3w:~/CRISPRCasFinder$ locate Unix/Sysexits.pm
/usr/local/lib/x86_64-linux-gnu/perl/5.30.0/Unix/Sysexits.pm

N.B: I am new in Linux, so facing issues. sorry for the inconvenience.

**Comment by dcouvin** [comment]
Hi Tushar,
Thank you for your message. Indeed I have also encountered this issue. On
my opinion, the best way to solve this issue is to deactivate conda
environment ("conda deactivate"), and run the CRISPRCasFinder tool using
the regular prompt without conda/bioconda.
Hope this will help.
Best regards,
David

**Comment by tasbd4** [comment]
Thank you @dcouvin for your response. 

I have tried deactivating conda environment but facing the same problem. Do you have any other solutions?

shishir@d3w:~/CRISPRCasFinder$ perl CRISPRCasFinder.pl 
Can't locate Date/Calc.pm in @INC (you may need to install the Date::Calc module) (@INC contains: /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2 /home/shishir/miniconda3/envs/genomics/lib/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/5.26.2 .) at CRISPRCasFinder.pl line 25.
BEGIN failed--compilation aborted at CRISPRCasFinder.pl line 25.

shishir@d3w:~/CRISPRCasFinder$ conda deactivate

shishir@d3w:~/CRISPRCasFinder$ perl CRISPRCasFinder.pl 
Can't locate Date/Calc.pm in @INC (you may need to install the Date::Calc module) (@INC contains: /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/site_perl/5.26.2 /home/shishir/miniconda3/envs/genomics/lib/5.26.2/x86_64-linux-thread-multi /home/shishir/miniconda3/envs/genomics/lib/5.26.2 .) at CRISPRCasFinder.pl line 25.
BEGIN failed--compilation aborted at CRISPRCasFinder.pl line 25.


If you like to know about the profile, here it is.

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
export MACSY_HOME=/home/shishir/CRISPRCasFinder/macsyfinder-1.0.5/
export PATH=/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/condabin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/bin:/home/shishir/miniconda3/envs/genomics/bin:/home/shishir/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export MACSY_HOME=/home/shishir/CRISPRCasFinder/macsyfinder-1.0.5/
export PATH=/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/condabin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/bin:/home/shishir/miniconda3/envs/genomics/bin:/home/shishir/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export MACSY_HOME=/home/shishir/CRISPRCasFinder/macsyfinder-1.0.5/
export PATH=/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/condabin:/home/shishir/CRISPRCasFinder/bin:/home/shishir/miniconda3/bin:/home/shishir/miniconda3/envs/genomics/bin:/home/shishir/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by dcouvin** [comment]
Hi @tasbd4 thank you for your message.
You can try to solve this perl module issue by trying to relocate perl module path in the perl script CRISPRCasFinder.pl by adding the line : use lib "directory_path/to_your_perl_modules"; you may not have complete access to directories/files in the system you use?
You can for example try to locate the module you need from your system. For example the following is the path to Date::Calc module in my system: /usr/local/share/perl/5.22.1/Date/Calc/Object.pm
Please look at the following pages to better solve your issue:
https://stackoverflow.com/questions/841785/how-do-i-include-a-perl-module-thats-in-a-different-directory/841812#841812
https://stackoverflow.com/questions/30659196/in-perl-cant-locate-packgename-pm-in-inc-error/30660241
Hope this will help.
Best regards,
David

**Comment by dcouvin** [comment]
If needed, here is another solution which may help: https://discourse.climb.ac.uk/t/cant-locate-in-inc/681/4 
Best regards,
David

**Comment by tasbd4** [comment]
Thank you, @dcouvin, for your concern. I have tried both ways but not working. 

I faced the same issue while used Ubuntu 18.04 LTS and solved it efficiently.
Now I have switched to Ubuntu 20.04 LTS, but this time I am not able to solve it by any means. I think there might be some issues of Miniconda with Ubuntu 20.04 build.

**Comment by dcouvin** [comment]
Dear @tasbd4 ,
Thank you for your message.
We will try to solve this in the future. I have not yet tried the tool with Ubuntu 20.04 LTS.
Best regards,
@dcouvin

**Comment by SergeyBaikal** [comment]
> Thank you, @dcouvin, for your concern. I have tried both ways but not working.
> 
> I faced the same issue while used Ubuntu 18.04 LTS and solved it efficiently.
> Now I have switched to Ubuntu 20.04 LTS, but this time I am not able to solve it by any means. I think there might be some issues of Miniconda with Ubuntu 20.04 build.

Good afternoon! Did you solve the problem? I have the same on Debian 10.

**Comment by SergeyBaikal** [comment]
Dear developers! I have the installation process for the second day. This is normal? Ubuntu 18.
`sudo bash installer_UBUNTU.sh
Extracting templates from packages: 100%
setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
Extracting templates from packages: 100%
Extracting templates from packages: 100%
`

**Comment by dcouvin** [comment]
Dear @SergeyBaikal ,
Thank you for your message. We have not tested the tool on Debian 10.
Otherwise, you can use the new Singularity (https://singularity.lbl.gov/) container available at : https://crisprcas.i2bc.paris-saclay.fr/Home/Download and in the readme page.
Best regards,
@dcouvin

**Comment by SergeyBaikal** [comment]
I used a container. (Debian 10, Vbox)
`$ singularity exec -B $PWD CrisprCasFinder.simg perl /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl -so /usr/local/CRISPRCasFinder/sel392v2.so -cf /usr/local/CRISPRCasFinder/CasFinder-2.0.3 -drpt /usr/local/CRISPRCasFinder/supplementary_files/repeatDirection.tsv -rpts /usr/local/CRISPRCasFinder/supplementary_files/Repeat_List.csv -cas -def G -out RES21092020_2 -in sequence.fasta
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_GB:en",
	LC_ALL = (unset),
	LANG = "en_GB.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error: file sequence.fasta not found. Please check that the file exists or enter a correct file name.
Usage: /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl [options] [-in] <filename>
type -version or -v to see the current version
type -help or -h for help`

**Comment by SergeyBaikal** [comment]
Everything turned out to be simple with the Singularity. Everything worked for me. Thanks!

**Comment by dcouvin** [comment]
This is great! Please just tell us how did you solve your previous
singularity error (locale settings....)?

Le jeu. 15 oct. 2020 23:00, Sergey Potapov <notifications@github.com> a
écrit :

**Comment by SergeyBaikal** [comment]
The problem with the CRISPRCasFinder standalone version could not be solved. I've tried different distributions (Debian 10, Ubuntu 18, Debian 10 Vbox). 
But after installing the singularity on debian 10, everything worked. I got results and I see a line after finishing work "Thank you for using /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl! Thank you for your patience!"

**Comment by dcouvin** [comment]
Ok, great! Singularity is very helpful! Thanks!

Le jeu. 15 oct. 2020 23:18, Sergey Potapov <notifications@github.com> a
écrit :
