### ISSUE TITLE
Getting multiple CAS types for a single CRISPR array

### ISSUE THREAD

**Issue by annagaines** [dcouvin/CRISPRCasFinder#27]
What does it mean multiple cas systems/types are reported in overlapping positions? Below is an example from the CRISPR-Cas_summary.tsv of my results. 

Sequence(s) | CRISPR array(s) | Nb CRISPRs | Evidence-levels | Cas cluster(s) | Nb Cas | Cas Types/Subtypes
-- | -- | -- | -- | -- | -- | --

NODE_16_length_64907_cov_27 | NODE_16_length_64907_cov_27_1[39949;42929]   (evidence-level=4), | 1 | Nb_arrays_evidence-level_1=0,Nb_arrays_evidence-level_2=0,Nb_arrays_evidence-level_3=0,Nb_arrays_evidence-level_4=1 | CAS-TypeIC[43401;48298],   CAS-TypeIA[8791;10563], CAS[8791;50522], | 3 | CAS (n=1), CAS-TypeIA (n=1), CAS-TypeIC   (n=1),
-- | -- | -- | -- | -- | -- | --

**Comment by dcouvin** [comment]
Hi @annagaines ,
Thank you for your message. I had not seen this message before. It is interesting! However, I don't know how to interpret it! Maybe you could try the online version or other tools to see if you get same results?
Best,
david
