### ISSUE TITLE
Different results for CasFinder in online and local runs

### ISSUE THREAD

**Issue by chahatupreti** [dcouvin/CRISPRCasFinder#28]
Hello!

Thank you for your wonderful software!
I had a question about running Casfinder. When I run the following genome (https://drive.google.com/file/d/1MolqP-lrjhngn2mO_XLq3QCUX1Fp_rR8/view?usp=sharing) on the online system, it reports multiple Cas genes. But when I run it on my local CrisprCasFinder installation using - 

`/.../CRISPRCasFinder.pl  -i /.../NZ_BJTO01000001.1.fa -out /.../NZ_BJTO01000001 -html 1  –keep 1 -cas 1 -ccvr 1 -ccc 1 -gscf 1 -cpuM 2
`
in the output, there are no Cas genes.

What do you think may be the cause of this discrepancy?

Thanks!
Chahat

**Comment by chahatupreti** [comment]
Hello!

Just wanted to check in and see if there were any ideas why this may be happening? I would be happy to give any more information if required.

Thank you,
Chahat

**Comment by dcouvin** [comment]
Dear Chahat, 
Thank you for your message, and sorry for the delayed response. You should try to reformulate your command line (taking into account examples provided). for example, you should not write number 1 after -cas, -keep, -ccvr, -ccc ,... options.
Hope this will help!
Best regards and happy 2021 !
David

**Comment by chahatupreti** [comment]
Thanks for that comment @dcouvin and a very happy new year to you too! I tried reformulating the command by removing all the 1's but still there was no Cas gene detected on the local run. Any ideas?

Thank you,
Chahat

**Comment by dcouvin** [comment]
Hi @chahatupreti ,
Thank you for your message. I have tried to launch the program with your sequence, and I obtained this results:

All CRISPRs = 1
All Cas = 1

[15:53:45] Thank you for using /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl! Thank you for your patience!

[15:53:45] The script lasted: 0 year(s) 0 month(s) 0 day(s) , 0 hour(s) 0 minute(s) 8 second(s)

I have used this command line : singularity exec -B $PWD CrisprCasFinder.simg perl /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl -so /usr/local/CRISPRCasFinder/sel392v2.so -cf /usr/local/CRISPRCasFinder/CasFinder-2.0.3 -drpt /usr/local/CRISPRCasFinder/supplementary_files/repeatDirection.tsv -rpts /usr/local/CRISPRCasFinder/supplementary_files/Repeat_List.csv -cas -def S -out RESNZsub -in NZ_BJTO01000001.fna

Maybe you should try again or use another machine (sometimes errors could occur when you have not sufficient rights on your current directory (maybe you could try to launch the program in your home (/home/...).

Hope this will help!
Best regards,
David

**Comment by chahatupreti** [comment]
Hi @dcouvin, I tried running this using Singularity and it worked too, even though I continue to not get the right CasFinder output on my local installation of CrisprCasFinder. Maybe I should try to reinstall it. 

Thank you!
