### ISSUE TITLE
mv error

### ISSUE THREAD

**Issue by rfroumine** [dcouvin/CRISPRCasFinder#3]
Approximately 50 out of my 2000 CRISPRCasFinder jobs did not finish due to error shown below. Do you know what could be causing this? Thank you

```
Traceback (most recent call last):
  File "/projects/js66/software/envs/crisprcasfinder/bin/macsyfinder", line 329, in <module>
    idx.build(force = config.build_indexes)
  File "/projects/js66/software/envs/crisprcasfinder/lib/python2.7/site-packages/macsypy/database.py", line 118, in build
    raise RuntimeError(msg)
RuntimeError: an error occurred during databases indexation see formatdb.log
No Cas results
mv: cannot move ‘ERR720254_29_1_2019_15_29_31/prodigal_size309’ to ‘ERR720254_29_1_2019_15_29_31/Prodigal/prodigal_size309’: Directory not empty
failure: "mv ERR720254_29_1_2019_15_29_31/prodigal_size309 ERR720254_29_1_2019_15_29_31/Prodigal", errorcode 256
```

**Comment by linnabrown** [comment]
I have the similar bug
```
Sequence number 34..Traceback (most recent call last):
  File "/home/ciillab/huangle/CRISPRCasFinder/bin/macsyfinder", line 329, in <module>
    idx.build(force = config.build_indexes)
  File "/home/ciillab/huangle/CRISPRCasFinder/macsyfinder-1.0.5/macsypy/database.py", line 118, in build
    raise RuntimeError(msg)
RuntimeError: an error occurred during databases indexation see formatdb.log

```

**Comment by dcouvin** [comment]
Thank you for your messages. The mv error could be due to permission issues. However, the RuntimeError has been fixed in recently updated version 4.2.19 of CRISPRCasFinder. Other issues will be tentatively fixed.

**Comment by erelior** [comment]
@rfroumine were you able to solve the mv issue? I have the exact same error

**Comment by rfroumine** [comment]
Hi @erelior. 
Yes actually! The issue in my case was that some contigs in the one fasta file had the same name, more specifically the part of their name after the | was the same. 

To solve this, I used this simple awk one-liner to change all my contig names to numbers 1 - n and then re-ran CRISPRCasFinder. (I’m sure something more sophisticated could be used to keep the base name of the contigs.)

awk '/^>/{print ">" ++i; next}{print}' < genome.fasta_edited.fasta > genome_renamed.fasta

Hope this works for you too.

**Comment by linnabrown** [comment]
coo. Thanks a lot!

**Comment by erelior** [comment]
@rfroumine worked for me. Thanks!!
