### ISSUE TITLE
vmatch2

### ISSUE THREAD

**Issue by drob2727** [dcouvin/CRISPRCasFinder#30]
I have been trying to use this program with singularity. I thought all the dependencies were going to be inside that package. I'm not sure how to install vmatch2 with singularity. Im including my command to show whats going on

(base) David-2:Downloads DavidMRobinson$  singularity exec -B $PWD CrisprCasFinder.simg perl /Users/DavidMRobinson/Downloads/CRISPRCasFinder/CRISPRCasFinder.pl -so /Users/DavidMRobinson/Downloads/CRISPRCasFinder/sel392v2.so -cf /Users/DavidMRobinson/Downloads/CRISPRCasFinder/CasFinder-2.0.3 -drpt /Users/DavidMRobinson/Downloads/CRISPRCasFinder/supplementary_files/repeatDirection.tsv -rpts /Users/DavidMRobinson/Downloads/CRISPRCasFinder/supplementary_files/Repeat_List.csv -cas -def G -out RES21092020_2 -in megahit_frx_bon_final_assembly.fasta
################################################################
# --> Welcome to /Users/DavidMRobinson/Downloads/CRISPRCasFinder/CRISPRCasFinder.pl (version 4.2.19) 
################################################################

vmatch2 is not installed, please install it and try again.
[    5.367732] reboot: Power down

**Comment by dcouvin** [comment]
Dear @drob2727 ,
Please note that you should try a command like this (taking into account the paths existing inside the singularity image): singularity exec -B $PWD CrisprCasFinder.simg perl /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl -so /usr/local/CRISPRCasFinder/sel392v2.so -cf /usr/local/CRISPRCasFinder/CasFinder-2.0.3 -drpt /usr/local/CRISPRCasFinder/supplementary_files/repeatDirection.tsv -rpts /usr/local/CRISPRCasFinder/supplementary_files/Repeat_List.csv -cas -def G -out RESULTfolder -in sequence.fasta
Hope this will help!
Best regards and happy 2021!
David

**Comment by drob2727** [comment]
Thanks! Do I need to have all the sequences from the metagenomes classified before I run this program or can I just use the contig names to see what comes up?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dcouvin** [comment]
You will need to have your sequences in a multi-FASTA file to run the program
