### ISSUE TITLE
MacSyFinder link outdated

### ISSUE THREAD

**Issue by oseias-r-junior** [dcouvin/CRISPRCasFinder#33]
Hello, 

Is there any update to be coming any soon? It seems installation will not work mainly because of the absence of a working MacSyFinder source link in the installation file.
Let me know how to proceed.
Thanks in advance!

[in]
`wget https://dl.bintray.com/gem-pasteur/MacSyFinder/macsyfinder-1.0.5.tar.gz >> $LOGFILE`

[out]
`Forbidden!`

Can I just comment on all the following and then install MacSyFinder manually through pip3?
    
    ```
    #install macsyfinder
    echo "Installation of MacSyFinder" >> $LOGFILE
    cd ${CURDIR}
    wget https://dl.bintray.com/gem-pasteur/MacSyFinder/macsyfinder-1.0.5.tar.gz >> $LOGFILE
    tar -xzf macsyfinder-1.0.5.tar.gz
    test -d bin ||  mkdir bin
    cd bin
    ln -s ../macsyfinder-1.0.5/bin/macsyfinder
    cd ${CURDIR}
    echo "add definition of MACSY_HOME (${CURDIR}/macsyfinder-1.0.5/) in .profile" >> $LOGFILE
    echo "export MACSY_HOME=${CURDIR}/macsyfinder-1.0.5/" >> $HOME/.profile

    echo "add bin folder ($CURDIR/bin) to the definition of PATH in $HOME/.profile" >> $LOGFILE
    echo "export PATH=${CURDIR}/bin:${PATH}" >> $HOME/.profile
```

**Comment by dcouvin** [comment]
Dear @oseias-r-junior ,
Thank you for your message.
An alternative link to get the tool (version 1.0.5) is: https://github.com/gem-pasteur/macsyfinder/archive/refs/tags/macsyfinder-1.0.5.tar.gz
Not sure that the new version of MacSyFinder will work properly when installed through pip3.
Maybe @bneron could help with this issue? (Bertrand could you please tell us if there is no difference regarding the JSON output file of the two versions of MacSyFinder?)
We will try to make an update soon!
Best,
@dcouvin

**Comment by oseias-r-junior** [comment]
Just to add one more thing, 
[fixed the issue with macsyfinder. thanks! :) ]

I'm currently getting this (although I've checked that vmatch is indeed installed and all the required files are in the respective folders) when giving the following command:

[in]
` perl CRISPRCasFinder.pl -cf CasFinder-2.0.3 -def General -cas -i install_test/sequence.fasta -out Results_test_install -keep`
[out]
```
################################################################
# --> Welcome to CRISPRCasFinder.pl (version 4.2.20)
################################################################


vmatch2 is not installed, please install it and try again.
``` 

Also,

typing,
`source ~/.profile`

inserts an error in my ~/.profile. It basically doesn't recognize windows folder with parenthesis. Like the folder (programs x86). Idk, if somebody else already mentioned that here. So, I had to vim to edit and exclude the 'error' insertions. BTW, I'm using WSL.

Thanks for the quick response, @dcouvin !
Best!

**Comment by dcouvin** [comment]
Dear @oseias-r-junior ,

Please note that when using Windows10 Subsystem for Linux (WSL), some additional programs (make, 
npm) must be installed. Please run: 
sudo apt-get install build-essential 
sudo apt-get install npm 
npm install parse-json 
 
Errors may occur when installing alignment and Json Perl libraries (Bio::Tools::Run::Alignment::Muscle 
and JSON::Parse).  
Their installation could necessitate the option "-f" of cpanm program: 
sudo cpanm -f Bio::Tools::Run::Alignment::Muscle 
sudo cpanm -f JSON::Parse"

Please also make sure that vmatch2 is available in your $PATH (you can try to execute it separately or re-install it).
Hope this will help!

Best,
@dcouvin
