### ISSUE TITLE
Multi-threads options

### ISSUE THREAD

**Issue by Chiongchih** [dcouvin/CRISPRCasFinder#34]
Does CRISPRCasFinder have an option for multi-threads? Thanks

**Comment by dcouvin** [comment]
Dear @Chiongchih,
Note that CRISPRCasFinder has an option for multi-threads when using cas gene detection program (MacSyFinder).
You can use the following option : -cpuMacSyFinder or -cpuM (followed by the number of threads you want).
Best regards,
@dcouvin
