### ISSUE TITLE
Installation of Date::Calc failed

### ISSUE THREAD

**Issue by JavierFFavieres** [dcouvin/CRISPRCasFinder#41]
I'm working on Mac. The first time I tried to install CRISPRCasFinder, it could not install Json::Parse. I installed it with conda and moved on. The second time the error was with Try::Tiny. Same solution. The third it was Test::Most. However,  the fourth time it was Date::Calc, which I have not been able to install via conda or anywhere else.

Installation of Perl and packages
Installation of Date::Calc...
Installation of Date::Calc failed see /Users/JFF/Desktop/Programas/CRISPRCasFinder-master/installer.2022-10-21-14:28:14.log for details.

**Comment by sallustfire** [comment]
I recently installed CRISPRCasFinder and has similar issues. Both Date::Calc and Unix::Sysexits depend on packages that have compiled extensions. If you're using conda, you'll need something like gcc_linux-64.

**Comment by dcouvin** [comment]
Thank you for your messages, I just updated the version of CRISPRCasFinder (v4.3.1 matching the new version of MacSyFinder v2.0).... Date::Calc and Unix::Sysexits modules are no more needed. Further improvements are in progress!

**Comment by dcouvin** [comment]
Please note that a new version has been released. It should work with conda/mamba environment...
