### ISSUE TITLE
Dependency issues using Singularity image

### ISSUE THREAD

**Issue by nh2740** [dcouvin/CRISPRCasFinder#42]
Hello,

I am trying to use the singularity image approach to run this program as I do not have root access in CentOS. I am using the latest image available and these files are all in the same directory. This is the command I am running:

`singularity exec -B $PWD CrisprCasFinder.simg perl CRISPRCasFinder.pl -in fasta.fasta`

I get this message when I run this: 
`vmatch2 is not installed, please install it and try again`

I looked through the perl script and it looks like there is a whole section of dependency checks where this is getting caught. I was under the impression the singularity image should cover the dependencies, but it looks like for some reason it is not.

I tried to get around this by installing the dependencies using a conda environment, but it looks like not all of the dependencies can be installed this way? (mkvtree2, vsubseqselect2)

Please let me know if you have a solution to this.

**Comment by dcouvin** [comment]
Hi @nh2740 ,
Please try the recently added conda/mamba environment installer.
Now, in the new version of CRISPRCasFinder, vmatch2, mkvtree2, and vsubseqselect2 have been replaced by vmatch, mkvtree, and vsubseqselect respectively.
Tell me if you encounter some issues in this new version.
Note that the "sel392v2.so" file is needed to run the tool (look at NEW.txt file for details).
Best,
David
