### ISSUE TITLE
How to use CRISPRCasFinder through singularity container

### ISSUE THREAD

**Issue by WoCer2019** [dcouvin/CRISPRCasFinder#46]
Thanks for your nice tool! I have only used Conda, and I have never used Singularity Container. 

First, I installed Singularity via mamba.
```
mamba create -n singularity -y singularity
```
Then, I downloaded the CrisprCasFinder.simg image from the CRISPR-Cas++ Download page.

When I ran the following code, an error happened.
```
mamba activate singularity

singularity exec -B $PWD CrisprCasFinder.simg perl /usr/local/CRISPRCasFinder/CRISPRCasFinder.pl -so /usr/local/CRISPRCasFinder/sel392v2.so -cf /usr/local/CRISPRCasFinder/CasFinder-2.0.3 -drpt /usr/local/CRISPRCasFinder/supplementary_files/repeatDirection.tsv -rpts /usr/local/CRISPRCasFinder/supplementary_files/Repeat_List.csv -cas -def G -out RES21092020_2 -in sequence.fasta

ERROR  : Image path doesn't exists
ABORT  : Retval = 255
```
Please tell me how to use CRISPRCasFinder through the singularity container. Thank you!

**Comment by dcouvin** [comment]
Dear @WoCer2019 ,

Thank you for your message.
Unfortunately, for unknown reasons, the tool doesn't work with the conda version of singularity. Please use conda environment installer to install the version 4.3.2.
conda env create -f ccf.environment.yml -n crisprcasfinder
conda activate crisprcasfinder
mamba init
mamba activate
mamba install -c bioconda macsyfinder=2.0
macsydata install -u CASFinder==3.1.0

Hope this helps! 
Best regards, 
@dcouvin

**Comment by WoCer2019** [comment]
Dear @dcouvin 

Thanks for your reply! The installation of this tool has been done. The output files include rawCRISPRs.fna, result.json, folder GFF, and folder TSV. Is it correct? Thanks again!

Best regards,
@WoCer2019

**Comment by dcouvin** [comment]
Dear @WoCer2019,
Thank you for your message. Yes it is correct!
Best regards,
@dcouvin

**Comment by WoCer2019** [comment]
Thanks!

**Comment by 473021677** [comment]
Hi,
    I have also used conda to install CRISPRCasFinder successfully. However, I do not know how to run this program. When I activated the conda environment and typed the command "perl CRISPRCasFinder.pl -v", it showed "Can't open perl script "CRISPRCasFinder.pl": No such file or directory". I really need your help. Thanks in advance.

Best regards,
Yang Yuan
