### ISSUE TITLE
CRISPRCasFinder.pl did not report any errors but produced three unknown core files

### ISSUE THREAD

**Issue by HZAU-YAYA** [dcouvin/CRISPRCasFinder#50]
Hi
These are my orders, CRISPRCasFinder.pl -in tt.fna -def General -cas -ccvr -ccc 50000 -gscf -keep -html -log -cpuM 8 -cpuP 8 --so sel392v2.so>tt.log.
CRISPRCasFinder.pl did not report any errors but produced three unknown core files
core.304026 core.304028 core.305136.
I don't know what these files represent, are they normal output from the program
Thanks

**Comment by dcouvin** [comment]
Hi @HZAU1702XBY,
Thank you for your message. Did you try to run the program without ">tt.log" ?
I think that this addition may generate the undesired files.
If you use the last version of the program, the following option " -def General" is no more required.
Hope this will work.
Best regards,
David

**Comment by HZAU-YAYA** [comment]
Hi David,
Thanks for your answer, I deleted "-def Genera"l and "&gt; tt.log". 
Program runs perfectly
